language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --no-interaction
  - mkdir -p build/logs
  - phpenv config-add config/config.ini

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
